[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Set the plugin to run but don't fail the build on low scores
    fail_deploy_on_score_thresholds = "false"
    
    # Set more reasonable thresholds for each report area
    [plugins.inputs.thresholds]
      performance = 0.5
      accessibility = 0.5
      best-practices = 0.5
      seo = 0.5

    # Only test the main page initially
    [[plugins.inputs.audits]]
      output_path = "reports/lighthouse.html"
      path = "index.html"

# Add cache headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"







