[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Set the plugin to run prior to deploy, failing the build if minimum thresholds aren't set 
    fail_deploy_on_score_thresholds = "true"
    
    # Set minimum thresholds for each report area
    [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 0.7

    # Define all audit configurations
    [[plugins.inputs.audits]]
      output_path = "reports/lighthouse.html"

    [[plugins.inputs.audits]]
      path = "contact.html"

    [[plugins.inputs.audits]]
      path = "pages/contact.html"

    [[plugins.inputs.audits]]
      serveDir = "pages"



